#!/bin/sh

MAILINGLIST=./english-names

for n in `cat $MAILINGLIST` ; do
	eval `echo $n | awk -F':' '{ print $1 " " $2}' |\
	sed 's/^\(.*\) \(.*\)$/NAME=\1 ADDRESS=\2/'`

(echo "$NAME:"
 echo ""
 echo "Hello from Oklahoma where I just finished our yearly blog:"
 echo ""
 echo "http://www.cs.ualberta.ca/~amaral/end-of-year-letter/2019"
 echo ""
 echo "Cheers, joy, and all the best!"
 echo ""
 echo "		Cheers,"
 echo ""
 echo "				Nelson, Scott & Daniel"
 echo ""
 echo "           /     "
 echo "    \     /  /   Jose Nelson Amaral - jamaral@ualberta.ca"
 echo "     )   /  (    Professor"
 echo "    /   /    \   Dept. of Computing Science - University of Alberta"
 echo "   (   /      )  Edmonton, Alberta, Canada, T6G 2E8"
 echo "    \ O      /   Fax: (780)492-1071"
 echo "     \      /    http://www.cs.ualberta.ca/~amaral"
 echo "       ---- "
 echo "") | Mail -s "End-of-Year Blog" $ADDRESS
 done
